Add Integration component to IntegrationsPage
kwickbit/kwickbit_frontend_v0 pull request #27
Opened 2023-11-24 16:12 UTC by MohsinGhani

https://github.com/kwickbit/kwickbit_frontend_v0/issues/12

2023-11-24 19:35 UTC, abstract829 commented
Please do not use too much hardcoded tailwind styles unless you need some specific color,

If you are taking the exact margins/paddings from the design, just use the closest one from tailwind

example: ```mt-[30px]``` -> ```mt-8 (32px)``` 
```pt-[8px]``` is the same as ```pt-2```
```text-[16px]``` is ```text-base```
etc...

please take a look at the styles and replace for the defaults tailwind offers

you can install [tailwind vscode extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) so when you writing code you can see what css do the classes apply

![Captura de pantalla 2023-11-24 a la(s) 16 31 04](https://github.com/kwickbit/kwickbit_frontend_v0/assets/56497105/4aa5dfa9-b559-4fe6-985b-80df587e10a9)

2023-11-24 20:54 UTC, MohsinGhani commented
> Please do not use too much hardcoded tailwind styles unless you need some specific color,
> 
> If you are taking the exact margins/paddings from the design, just use the closest one from tailwind
> 
> example: `mt-[30px]` -> `mt-8 (32px)` `pt-[8px]` is the same as `pt-2` `text-[16px]` is `text-base` etc...
> 
> please take a look at the styles and replace for the defaults tailwind offers
> 
> you can install [tailwind vscode extension](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) so when you writing code you can see what css do the classes apply
> 
> ![Captura de pantalla 2023-11-24 a la(s) 16 31 04](https://private-user-images.githubusercontent.com/56497105/285534060-4aa5dfa9-b559-4fe6-985b-80df587e10a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTk0MTYsIm5iZiI6MTcwMDg1OTExNiwicGF0aCI6Ii81NjQ5NzEwNS8yODU1MzQwNjAtNGFhNWRmYTktYjU1OS00ZmU2LTk4NWItODBkZjU4N2UxMGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDIwNTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYWY1NWQ4ZTA5MjRlMjhmY2EzNjg2MDk0NTcxYjA1NzM2NjQ3Mzk5NTZlNjBhYWFiMTYwYWU5YmY5YTQyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wrIt0eEkdMTSzkhXHvCbCi5wb1j3kE-NkaExwfthM2M)

Thank You @abstract829 for the review. I will be careful about it. Please feel free to add comments if you feel any kind of inconsistency in the code.

2023-11-27 05:55 UTC, MohsinGhani commented
Hi @abstract829, can you please take a look at the code now?

Thank You!

2023-11-27 11:37 UTC, abstract829 requested changes
Great, looks a lot better, I leave some small improvements and we are ok

2023-11-27 11:37 UTC, abstract829 commented on src/components/integration/index.tsx
```bash
<p className="text-base text-[#171A1FFF] font-bold">Quickbooks</p>
<p className="text-base text-[#9095A1FF] font-bold">Accounting</p>
```
![Captura de pantalla 2023-11-27 a la(s) 08 28 25](https://github.com/kwickbit/kwickbit_frontend_v0/assets/56497105/01c1df57-8c3e-4a37-b8e0-9dcd47961505)
![Captura de pantalla 2023-11-27 a la(s) 08 28 31](https://github.com/kwickbit/kwickbit_frontend_v0/assets/56497105/9ec5ba53-0dc7-4dad-8173-1802c5e30993)

besides these color you can see "neutral-500" and "neutral-900" which means you can use text-neutral-500 and text-neutral-900 in tailwind, please change

![Captura de pantalla 2023-11-27 a la(s) 08 27 23](https://github.com/kwickbit/kwickbit_frontend_v0/assets/56497105/980655ec-bf73-4628-94c1-5fbf73dfa8ad)

Here the button is cut off, you can remove the ```w-20``` and wrap the button in a div and should be fine, or make your own button is also fine for now, the primarybutton is not so dynamic

2023-11-28 15:37 UTC, abstract829 approved these changes

2023-11-28 15:43 UTC, merged