Built the transaction page - issue17_1
kwickbit/kwickbit_frontend_v0 pull request #32
Opened 2023-11-25 08:38 UTC by geniusFulldev

Added non-set warning to each row

2023-11-26 23:43 UTC, abstract829 requested changes
Looks good, I just write some improvements in the fetch function and we are ok

2023-11-26 23:43 UTC, abstract829 commented on src/services/transactions.ts
This functions looks a bit hard to read, please consider make some changes:

```bash
export const fetchTransactions = async (): Promise<TransactionAPIResult> => {
  const ret = await fetch("/data/transactions.json");
  if( !ret.ok ) {
    throw new Error(ret.statusText);
  }
  const data:TransactionAPIResult = await ret.json();
  if( data.transactions ) {
    for(const transaction of data.transactions) {
      const currency = transaction.from.detail?.type === 'currency'? transaction.from.detail.symbol: (transaction.to.detail?.type === 'currency'? transaction.to.detail.symbol: null );
      const token = transaction.to.detail?.type === 'token'? transaction.to.detail.symbol: (transaction.from.detail?.type === 'token'? transaction.from.detail.symbol: null );
      let nonSetMapping = false;
      if( data.non_set_currencies ) {
        nonSetMapping = !!data.non_set_currencies.find(item => item.currency === currency && item.token === token );
      }
      transaction.currencyMapping = {
        currency, 
        token,
        nonSetMapping
      }
    }
  }
  ```
  
Please consider using separate 'if' statements instead of nested ternary operators for improved readability, especially when dealing with multiple conditions.

```bash

const fromDetail = transaction.from.detail;
const toDetail = transaction.to.detail;

if (fromDetail?.type === "currency") {
  currency = fromDetail.symbol;
}

if (toDetail?.type === "currency") {
  currency = toDetail.symbol;
}

....
```
Also consider using the map function to create a new array of transactions instead of mutating the original object. This promotes immutability and makes it clearer how transactions are transformed.
  
 
  ```bash
    const transactions = data.transactions.map((transaction) => {

    ...

    return {
      ...transaction,
      currencyMapping: {
        currency,
        token,
        nonSetMapping,
      },
    };

  });


return {...data, transactions};
  ```

2023-11-26 23:48 UTC, abstract829 commented on src/services/transactions.ts
Also fetchTransaction should only do the "fetch to transactions" and the transform function should be in another one

2023-11-27 08:15 UTC, geniusFulldev commented on src/services/transactions.ts
Ok, I will do

2023-11-27 11:12 UTC, abstract829 approved these changes

2023-11-27 11:15 UTC, merged